Added cin_cam reading, as well as POINT3D
TheLegendOfMataNui/Shoefitter-DX pull request #10
Opened 2019-03-23 19:35 UTC by OndrikB

I don't know if there's any errors. If you find any, tell me.

2019-03-23 19:53 UTC, Vraiment requested changes
Also, not as important but can you remove the duplicated empty lines and leave a single empty line between method names (ex: `Point3D.ToString()` doesn't have a preceding empty line)

2019-03-23 19:53 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Frame.cs
> +        internal const int BINARY_SIZE = 28;
Not needed

2019-03-23 19:53 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Camera.cs
> +        internal const int BINARY_SIZE = 20; //TODO: I don't know what I should count
Not needed

2019-03-23 19:53 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Frame.cs
> +        public override string ToString()
Use string interpolation:

`return $"Time={Time}, Position={Position}, Target={Target}"`

2019-03-23 19:53 UTC, Vraiment commented on SAGESharp/SLB/Point3D.cs
> +        public override string ToString()
Use string interpolation:

`return $"X={X}, Y={Y}, Z={Z}";`

2019-03-23 19:53 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Camera.cs
> +        public override string ToString()
Use string interpolation:

```
return $"ViewAngle={ViewAngle}," +
    $"SpinMaskTimes1={SpinMasktimes1}," +
    $"SpinMaskTimes2={SpinMasktimes2}," +
    $"SpinMaskTimes3={SpinMasktimes3}," +
    $"Frames={Frames?.Let(frames => "[(" + string.Join("), (") + ")]") ?? "null"}";
```

You will also need to add: `using Konvenience;` at the top

2019-03-23 20:14 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Frame.cs
> +        public override string ToString()
We missed a semicolon at the end of the line :P

2019-03-23 20:17 UTC, Vraiment commented on SAGESharp/SLB/Cinematic/Camera/Camera.cs
> +        public override string ToString()
I missed here a chunk, the last line should be:

```
    $"Frames={Frames?.Let(frames => "[(" + string.Join("), (", frames) + ")]") ?? "null"}";
```

2019-03-23 20:17 UTC, Vraiment requested changes
See comments

2019-03-25 06:37 UTC, Vraiment approved these changes

2019-03-25 06:38 UTC, epicabsol approved these changes

2019-03-27 09:13 UTC, Vraiment commented
Tested reading a couple of files with these clases and the smart reader and it seems it works so I'm merging these.

2019-03-27 09:13 UTC, merged